
package br.com.caelum.correios.ws;

import java.math.BigDecimal;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalcPrecoPrazoWSSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalcPrecoPrazoWSSoap {


    /**
     * 
     * @param sCdAvisoRecebimento
     * @param sDsSenha
     * @param sCepDestino
     * @param nVlValorDeclarado
     * @param nVlLargura
     * @param nVlComprimento
     * @param nCdEmpresa
     * @param nVlPeso
     * @param nCdFormato
     * @param sCdMaoPropria
     * @param sCepOrigem
     * @param nVlAltura
     * @param nCdServico
     * @param nVlDiametro
     * @return
     *     returns br.com.caelum.correios.ws.CResultado
     */
    @WebMethod(operationName = "CalcPrecoPrazo", action = "http://tempuri.org/CalcPrecoPrazo")
    @WebResult(name = "CalcPrecoPrazoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcPrecoPrazo", targetNamespace = "http://tempuri.org/", className = "br.com.caelum.correios.ws.CalcPrecoPrazo")
    @ResponseWrapper(localName = "CalcPrecoPrazoResponse", targetNamespace = "http://tempuri.org/", className = "br.com.caelum.correios.ws.CalcPrecoPrazoResponse")
    public CResultado calcPrecoPrazo(
        @WebParam(name = "nCdEmpresa", targetNamespace = "http://tempuri.org/")
        String nCdEmpresa,
        @WebParam(name = "sDsSenha", targetNamespace = "http://tempuri.org/")
        String sDsSenha,
        @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/")
        String nCdServico,
        @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        String sCepOrigem,
        @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        String sCepDestino,
        @WebParam(name = "nVlPeso", targetNamespace = "http://tempuri.org/")
        String nVlPeso,
        @WebParam(name = "nCdFormato", targetNamespace = "http://tempuri.org/")
        int nCdFormato,
        @WebParam(name = "nVlComprimento", targetNamespace = "http://tempuri.org/")
        BigDecimal nVlComprimento,
        @WebParam(name = "nVlAltura", targetNamespace = "http://tempuri.org/")
        BigDecimal nVlAltura,
        @WebParam(name = "nVlLargura", targetNamespace = "http://tempuri.org/")
        BigDecimal nVlLargura,
        @WebParam(name = "nVlDiametro", targetNamespace = "http://tempuri.org/")
        BigDecimal nVlDiametro,
        @WebParam(name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/")
        String sCdMaoPropria,
        @WebParam(name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/")
        BigDecimal nVlValorDeclarado,
        @WebParam(name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/")
        String sCdAvisoRecebimento);

    /**
     * 
     * @param sDtCalculo
     * @param sCdAvisoRecebimento
     * @param sDsSenha
     * @param sCepDestino
     * @param nVlValorDeclarado
     * @param nVlLargura
     * @param nVlComprimento
     * @param nCdEmpresa
     * @param nVlPeso
     * @param nCdFormato
     * @param sCdMaoPropria
     * @param sCepOrigem
     * @param nVlAltura
     * @param nCdServico
     * @param nVlDiametro
     * @return
     *     returns br.com.caelum.correios.ws.CResultado
     */
    @WebMethod(operationName = "CalcPrecoPrazoData", action = "http://tempuri.org/CalcPrecoPrazoData")
    @WebResult(name = "CalcPrecoPrazoDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcPrecoPrazoData", targetNamespace = "http://tempuri.org/", className = "br.com.caelum.correios.ws.CalcPrecoPrazoData")
    @ResponseWrapper(localName = "CalcPrecoPrazoDataResponse", targetNamespace = "http://tempuri.org/", className = "br.com.caelum.correios.ws.CalcPrecoPrazoDataResponse")
    public CResultado calcPrecoPrazoData(
        @WebParam(name = "nCdEmpresa", targetNamespace = "http://tempuri.org/")
        String nCdEmpresa,
        @WebParam(name = "sDsSenha", targetNamespace = "http://tempuri.org/")
        String sDsSenha,
        @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/")
        String nCdServico,
        @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        String sCepOrigem,
        @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        String sCepDestino,
        @WebParam(name = "nVlPeso", targetNamespace = "http://tempuri.org/")
        String nVlPeso,
        @WebParam(name = "nCdFormato", targetNamespace = "http://tempuri.org/")
        int nCdFormato,
        @WebParam(name = "nVlComprimento", targetNamespace = "http://tempuri.org/")
        BigDecimal nVlComprimento,
        @WebParam(name = "nVlAltura", targetNamespace = "http://tempuri.org/")
        BigDecimal nVlAltura,
        @WebParam(name = "nVlLargura", targetNamespace = "http://tempuri.org/")
        BigDecimal nVlLargura,
        @WebParam(name = "nVlDiametro", targetNamespace = "http://tempuri.org/")
        BigDecimal nVlDiametro,
        @WebParam(name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/")
        String sCdMaoPropria,
        @WebParam(name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/")
        BigDecimal nVlValorDeclarado,
        @WebParam(name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/")
        String sCdAvisoRecebimento,
        @WebParam(name = "sDtCalculo", targetNamespace = "http://tempuri.org/")
        String sDtCalculo);

    /**
     * 
     * @param sCdAvisoRecebimento
     * @param sDsSenha
     * @param sCepDestino
     * @param nVlValorDeclarado
     * @param nVlLargura
     * @param nVlComprimento
     * @param nCdEmpresa
     * @param nVlPeso
     * @param nCdFormato
     * @param sCdMaoPropria
     * @param sCepOrigem
     * @param nVlAltura
     * @param nCdServico
     * @param nVlDiametro
     * @return
     *     returns br.com.caelum.correios.ws.CResultado
     */
    @WebMethod(operationName = "CalcPreco", action = "http://tempuri.org/CalcPreco")
    @WebResult(name = "CalcPrecoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcPreco", targetNamespace = "http://tempuri.org/", className = "br.com.caelum.correios.ws.CalcPreco")
    @ResponseWrapper(localName = "CalcPrecoResponse", targetNamespace = "http://tempuri.org/", className = "br.com.caelum.correios.ws.CalcPrecoResponse")
    public CResultado calcPreco(
        @WebParam(name = "nCdEmpresa", targetNamespace = "http://tempuri.org/")
        String nCdEmpresa,
        @WebParam(name = "sDsSenha", targetNamespace = "http://tempuri.org/")
        String sDsSenha,
        @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/")
        String nCdServico,
        @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        String sCepOrigem,
        @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        String sCepDestino,
        @WebParam(name = "nVlPeso", targetNamespace = "http://tempuri.org/")
        String nVlPeso,
        @WebParam(name = "nCdFormato", targetNamespace = "http://tempuri.org/")
        int nCdFormato,
        @WebParam(name = "nVlComprimento", targetNamespace = "http://tempuri.org/")
        BigDecimal nVlComprimento,
        @WebParam(name = "nVlAltura", targetNamespace = "http://tempuri.org/")
        BigDecimal nVlAltura,
        @WebParam(name = "nVlLargura", targetNamespace = "http://tempuri.org/")
        BigDecimal nVlLargura,
        @WebParam(name = "nVlDiametro", targetNamespace = "http://tempuri.org/")
        BigDecimal nVlDiametro,
        @WebParam(name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/")
        String sCdMaoPropria,
        @WebParam(name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/")
        BigDecimal nVlValorDeclarado,
        @WebParam(name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/")
        String sCdAvisoRecebimento);

    /**
     * 
     * @param sDtCalculo
     * @param sCdAvisoRecebimento
     * @param sDsSenha
     * @param sCepDestino
     * @param nVlValorDeclarado
     * @param nVlLargura
     * @param nVlComprimento
     * @param nCdEmpresa
     * @param nVlPeso
     * @param nCdFormato
     * @param sCdMaoPropria
     * @param sCepOrigem
     * @param nVlAltura
     * @param nCdServico
     * @param nVlDiametro
     * @return
     *     returns br.com.caelum.correios.ws.CResultado
     */
    @WebMethod(operationName = "CalcPrecoData", action = "http://tempuri.org/CalcPrecoData")
    @WebResult(name = "CalcPrecoDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcPrecoData", targetNamespace = "http://tempuri.org/", className = "br.com.caelum.correios.ws.CalcPrecoData")
    @ResponseWrapper(localName = "CalcPrecoDataResponse", targetNamespace = "http://tempuri.org/", className = "br.com.caelum.correios.ws.CalcPrecoDataResponse")
    public CResultado calcPrecoData(
        @WebParam(name = "nCdEmpresa", targetNamespace = "http://tempuri.org/")
        String nCdEmpresa,
        @WebParam(name = "sDsSenha", targetNamespace = "http://tempuri.org/")
        String sDsSenha,
        @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/")
        String nCdServico,
        @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        String sCepOrigem,
        @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        String sCepDestino,
        @WebParam(name = "nVlPeso", targetNamespace = "http://tempuri.org/")
        String nVlPeso,
        @WebParam(name = "nCdFormato", targetNamespace = "http://tempuri.org/")
        int nCdFormato,
        @WebParam(name = "nVlComprimento", targetNamespace = "http://tempuri.org/")
        BigDecimal nVlComprimento,
        @WebParam(name = "nVlAltura", targetNamespace = "http://tempuri.org/")
        BigDecimal nVlAltura,
        @WebParam(name = "nVlLargura", targetNamespace = "http://tempuri.org/")
        BigDecimal nVlLargura,
        @WebParam(name = "nVlDiametro", targetNamespace = "http://tempuri.org/")
        BigDecimal nVlDiametro,
        @WebParam(name = "sCdMaoPropria", targetNamespace = "http://tempuri.org/")
        String sCdMaoPropria,
        @WebParam(name = "nVlValorDeclarado", targetNamespace = "http://tempuri.org/")
        BigDecimal nVlValorDeclarado,
        @WebParam(name = "sCdAvisoRecebimento", targetNamespace = "http://tempuri.org/")
        String sCdAvisoRecebimento,
        @WebParam(name = "sDtCalculo", targetNamespace = "http://tempuri.org/")
        String sDtCalculo);

    /**
     * 
     * @param sCepDestino
     * @param sCepOrigem
     * @param nCdServico
     * @return
     *     returns br.com.caelum.correios.ws.CResultado
     */
    @WebMethod(operationName = "CalcPrazo", action = "http://tempuri.org/CalcPrazo")
    @WebResult(name = "CalcPrazoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcPrazo", targetNamespace = "http://tempuri.org/", className = "br.com.caelum.correios.ws.CalcPrazo")
    @ResponseWrapper(localName = "CalcPrazoResponse", targetNamespace = "http://tempuri.org/", className = "br.com.caelum.correios.ws.CalcPrazoResponse")
    public CResultado calcPrazo(
        @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/")
        String nCdServico,
        @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        String sCepOrigem,
        @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        String sCepDestino);

    /**
     * 
     * @param sDtCalculo
     * @param sCepDestino
     * @param sCepOrigem
     * @param nCdServico
     * @return
     *     returns br.com.caelum.correios.ws.CResultado
     */
    @WebMethod(operationName = "CalcPrazoData", action = "http://tempuri.org/CalcPrazoData")
    @WebResult(name = "CalcPrazoDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CalcPrazoData", targetNamespace = "http://tempuri.org/", className = "br.com.caelum.correios.ws.CalcPrazoData")
    @ResponseWrapper(localName = "CalcPrazoDataResponse", targetNamespace = "http://tempuri.org/", className = "br.com.caelum.correios.ws.CalcPrazoDataResponse")
    public CResultado calcPrazoData(
        @WebParam(name = "nCdServico", targetNamespace = "http://tempuri.org/")
        String nCdServico,
        @WebParam(name = "sCepOrigem", targetNamespace = "http://tempuri.org/")
        String sCepOrigem,
        @WebParam(name = "sCepDestino", targetNamespace = "http://tempuri.org/")
        String sCepDestino,
        @WebParam(name = "sDtCalculo", targetNamespace = "http://tempuri.org/")
        String sDtCalculo);

}
